<?php

namespace App\Controller\Admin;

use App\Controller\ImportListController;
use App\Entity\TvShow;
use App\Repository\TvShowRepository;
use App\Service\FilesReaderService;
use App\Service\ImportService;
use Doctrine\ORM\EntityManagerInterface;
use EasyCorp\Bundle\EasyAdminBundle\Config\Action;
use EasyCorp\Bundle\EasyAdminBundle\Config\Actions;
use EasyCorp\Bundle\EasyAdminBundle\Config\Crud;
use EasyCorp\Bundle\EasyAdminBundle\Config\KeyValueStore;
use EasyCorp\Bundle\EasyAdminBundle\Context\AdminContext;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractCrudController;
use EasyCorp\Bundle\EasyAdminBundle\Dto\EntityDto;
use EasyCorp\Bundle\EasyAdminBundle\Field\AssociationField;
use EasyCorp\Bundle\EasyAdminBundle\Field\IdField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextField;
use EasyCorp\Bundle\EasyAdminBundle\Router\AdminUrlGenerator;
use Symfony\Component\DependencyInjection\ParameterBag\ParameterBagInterface;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Response;

class TvShowCrudController extends AbstractCrudController
{
    protected FilesReaderService $filesystemReader;
    protected EntityManagerInterface $entityManager;
    protected ParameterBagInterface $parameterBag;
    protected AdminUrlGenerator $adminUrlGenerator;
    protected ImportService $importService;

    public function __construct(
        FilesReaderService $filesystemReader,
        EntityManagerInterface $entityManager,
        ParameterBagInterface $parameterBag,
        AdminUrlGenerator $adminUrlGenerator,
        ImportService $importService
    ) {
        $this->filesystemReader = $filesystemReader;
        $this->entityManager = $entityManager;
        $this->parameterBag = $parameterBag;
        $this->adminUrlGenerator = $adminUrlGenerator;
        $this->importService = $importService;
    }

    public static function getEntityFqcn(): string
    {
        return TvShow::class;
    }

    public function configureFields(string $pageName): iterable
    {
        return [
            TextField::new(TvShow::name),
            TextField::new(TvShow::slug),
            IdField::new(TvShow::theTvDbId),
            AssociationField::new(TvShow::episodes)
                ->onlyOnDetail()
                ->setTemplatePath('admin/tvshow/crud/field/episodes.html.twig'),
        ];
    }

    public function configureCrud(Crud $crud): Crud
    {
        return parent::configureCrud($crud); // TODO: Change the autogenerated stub
    }

    public function configureActions(Actions $actions): Actions
    {
        $globalSearchAction = Action::new(
            'app_search_tv_show',
            'Suche',
            'fas fa-search'
        )
            ->createAsGlobalAction()
            ->linkToRoute('app_search_tv_show');

        $globalImportAction = Action::new(
            'app_import_tvshow_list',
            'Liste importieren',
            'fas fa-file'
        )
            ->createAsGlobalAction()
            ->linkToRoute('app_import_all_list');

        $globalImportAllEpisodesAction = Action::new(
            'app_import_all_episodes',
            'TVDB Episoden importieren',
            'fas fa-tv'
        )
            ->createAsGlobalAction()
            ->linkToCrudAction('redirectToImportEpisodesAction');

        $imporTvShowListAction = Action::new(
            'app_import_tvshow_list',
            'Liste importieren',
            'fas fa-file'
        )
            ->linkToCrudAction('redirectToImportListAction');

        $importEpisodesAction = Action::new(
            'app_import_episodes',
            'TVDB Episoden importieren',
            'fas fa-tv'
        )
            ->linkToCrudAction('redirectToImportEpisodesAction');

        $actions->add(Crud::PAGE_INDEX, $globalSearchAction);
        $actions->add(Crud::PAGE_INDEX, $globalImportAction);
        $actions->add(Crud::PAGE_INDEX, $globalImportAllEpisodesAction);
        $actions->add(Crud::PAGE_INDEX, Action::DETAIL);

        $actions->add(Crud::PAGE_DETAIL, $imporTvShowListAction);
        $actions->add(Crud::PAGE_DETAIL, $globalSearchAction);
        $actions->add(Crud::PAGE_DETAIL, $importEpisodesAction);

        $actions->add(Crud::PAGE_NEW, $globalSearchAction);

        return parent::configureActions($actions);
    }

    public function index(AdminContext $context)
    {
        return $this->render('admin/tvshow/page/index.html.twig', parent::index($context)->all());
    }

    public function detail(AdminContext $context): KeyValueStore|Response
    {
        $this->filesystemReader->readTvShowDirectory($context->getEntity()->getInstance());

        return parent::detail($context);
    }

    public function createNewFormBuilder(EntityDto $entityDto, KeyValueStore $formOptions, AdminContext $context): FormBuilderInterface
    {
        /** @var TvShow $entry */
        $entry = $entityDto->getInstance();
        $formBuilder = parent::createNewFormBuilder($entityDto, $formOptions, $context);

        if ($name = $context->getRequest()->get(TvShow::name)) {
            $entry->setName($name);
        }

        if ($theTvDbId = $context->getRequest()->get(TvShow::theTvDbId)) {
            $entry->setTheTvDbId($theTvDbId);
        }

        if ($slug = $context->getRequest()->get(TvShow::slug)) {
            $entry->setSlug($slug);
        }

        return $formBuilder;
    }

    public function redirectToImportListAction(AdminContext $context): RedirectResponse
    {
        return $this->redirect($this->adminUrlGenerator
            ->setController(ImportListController::class)
            ->setDashboard(DashboardController::class)
            ->setRoute('app_import_tvshow_list', ['tvShowId' => $context->getEntity()->getInstance()->getId()])
            ->generateUrl());
    }

    public function redirectToImportEpisodesAction(AdminContext $context, TvShowRepository $tvShowRepository): RedirectResponse
    {
        $redirectUrl = $this->adminUrlGenerator
            ->setController(__CLASS__)
            ->setDashboard(DashboardController::class)
        ;

        if (($tvShow = $context->getEntity()->getInstance()) && $tvShow instanceof TvShow) {
            $this->importService->importTvShowDataFromTheTVDB($tvShow);
            $redirectUrl
                ->setAction(Action::DETAIL)
                ->setEntityId($tvShow->getId());
        } else {
            foreach ($tvShowRepository->findAll() as $tvShow) {
                $this->importService->importTvShowDataFromTheTVDB($tvShow);
            }

            $redirectUrl
                ->setAction(Action::INDEX);
        }

        return $this->redirect($redirectUrl->generateUrl());
    }
}
