parameters:
    thetvdb.base_uri: '%env(THETVDB_BASE_URI)%'
    thetvdb.token: '%env(THETVDB_TOKEN)%'
    thetvdb.apikey: '%env(THETVDB_APIKEY)%'
    thetvdb.pin: '%env(THETVDB_PIN)%'
    tvshow.filesystem.base_directory: '%env(TVSHOWS_BASE_DIRECTORY)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
